# Generated by Django 6.0.6 on 2026-06-17 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '__first__'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CusotmUser',
            new_name='CustomUser',
        ),
    ]
