# Generated by Django 6.0.6 on 2026-06-26 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='customerprofile_id',
        ),
        migrations.RemoveField(
            model_name='address',
            name='managerprofile_id',
        ),
        migrations.RemoveField(
            model_name='clientpicture',
            name='customerprofile_id',
        ),
        migrations.RemoveField(
            model_name='clientpicture',
            name='managerprofile_id',
        ),
        migrations.AddField(
            model_name='address',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientpicture',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
