# Generated by Django 6.0.6 on 2026-06-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_remove_address_customerprofile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
