# Generated by Django 6.0.6 on 2026-06-17 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_customerprofile_managerprofile_address_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='lath',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='lenght',
            new_name='longitude',
        ),
    ]
