# Generated by Django 6.0.6 on 2026-06-22 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='general.basemodel')),
                ('expire_datetime', models.DateTimeField()),
                ('code', models.CharField(max_length=5)),
                ('percent', models.IntegerField()),
                ('max_amount', models.DecimalField(decimal_places=1, max_digits=10)),
                ('order_min_amount', models.DecimalField(decimal_places=1, max_digits=10)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('general.basemodel',),
        ),
    ]
