# Generated by Django 6.0.6 on 2026-06-25 14:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitemmodel',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AddField(
            model_name='orderitemmodel',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='cartitemmodel',
            name='cart_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.cartmodel'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='total_amount',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitemmodel',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.ordermodel'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='taxed_amount',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='total_amount',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=10),
        ),
    ]
