# Generated by Django 6.0.6 on 2026-06-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemmodel',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cartitemmodel',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
