# Generated by Django 6.0.6 on 2026-07-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountmodel',
            name='is_active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AlterField(
            model_name='orderitemmodel',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitemmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
