# Generated by Django 6.0.6 on 2026-06-22 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_user_is_customer'),
        ('general', '0001_initial'),
        ('sale', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='general.basemodel')),
                ('total_amount', models.DecimalField(decimal_places=1, max_digits=10)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('general.basemodel',),
        ),
        migrations.CreateModel(
            name='CartItemModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='general.basemodel')),
                ('price', models.DecimalField(decimal_places=1, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=1, max_digits=10)),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.cartmodel')),
            ],
            bases=('general.basemodel',),
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='general.basemodel')),
                ('total_amount', models.DecimalField(decimal_places=1, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=1, max_digits=10)),
                ('taxed_amount', models.DecimalField(decimal_places=1, max_digits=10)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.address')),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.cartmodel')),
                ('discount_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.discountmodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('general.basemodel',),
        ),
        migrations.CreateModel(
            name='OrderItemModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='general.basemodel')),
                ('quantity', models.DecimalField(decimal_places=1, max_digits=10)),
                ('price', models.DecimalField(decimal_places=1, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=1, max_digits=10)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.ordermodel')),
            ],
            bases=('general.basemodel',),
        ),
    ]
