# Generated by Django 6.0.6 on 2026-07-01 04:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_alter_cartitemmodel_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemmodel',
            name='amount',
            field=models.DecimalField(db_default=Decimal('0'), decimal_places=1, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='cartitemmodel',
            name='quantity',
            field=models.IntegerField(db_default=0, default=0),
        ),
    ]
