# Generated by Django 6.0.6 on 2026-07-01 05:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_alter_cartitemmodel_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemmodel',
            name='amount',
            field=models.DecimalField(db_default=Decimal('0'), decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='cartitemmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
